### PR TITLE
Fix open class to allow override of present and dismiss

### PR DESCRIPTION
**Pull request by hons82**
This allows to easily create controllers with custom content

### CODE REVIEW

**Comment by sberrevoets** [comment]
Hey @hons82, thanks for submitting. Could you explain a little what you're trying to do that requires opening `AlertController`? I'm hesitant to open it up unless absolutely necessary so would like to understand your need for this and see if there's a different way to do what you want.

**Comment by hons82** [comment]
Hi, something really simple. 
I created a subclass of it that in the show method instantiates a custom loader view...
And destroys it on dismiss.

**Comment by sberrevoets** [comment]
Do you need additional state for that? If not, you could simply extend the class without it being `open`. If you do need additional state (which seems unlikely, though I don't know the exact details of your case), you should consider composition over inheritance to hold that additional state.

**Comment by sberrevoets** [comment]
Closing this for inactivity.

**Pull request closed without merging**
