### PR TITLE
Added imageView, accessoryView for action sheet cells

### PR DESCRIPTION
**Pull request by futuretap**
Added the following properties on `AlertAction`:

- `imageView`: left-aligned image view. If set, the title label will be left-aligned instead of centered.
- `accessoryView`: right-aligned accessory view. If set, the title label will be left-aligned instead of centered.

Added on `AlertVisualStyle` to override the text alignment of the title label:
`func setCellLabelAlignment(alignment: NSTextAlignment)`.

Using these properties, one can implement action sheets like this:

accessoryviews

### CODE REVIEW

**Comment by gereons** [comment]
Is there a chance this can get updated and merged? It's precisely what I need in my app right now...

**Comment by gereons** [comment]
@futuretap : I have a merged version working at https://github.com/gereons/SDCAlertView/tree/actionAccessoryViews

Do you maybe have any idea how to avoid these runtime warnings? (printed by `loadNibNamed()` in AlertController.swift:177)

> 2020-04-17 09:15:14.149279+0200 Example[3330:67265] [LayoutConstraints] The view hierarchy is not prepared for the constraint: <NSLayoutConstraint:0x600002bbe300 _UIVisualEffectContentView:0x7ff493e09d70.top == UIVisualEffectView:0x7ff493e09b90.top   (inactive)>
	When added to a view, the constraint's items must be descendants of that view (or the view itself). This will crash if the constraint needs to be resolved before the view hierarchy is assembled. Break on -[UIView(UIConstraintBasedLayout) _viewHierarchyUnpreparedForConstraint:] to debug.
2020-04-17 09:15:14.149464+0200 Example[3330:67265] [LayoutConstraints] The view hierarchy is not prepared for the constraint: <NSLayoutConstraint:0x600002bbe940 UIVisualEffectView:0x7ff493e09b90.trailing == _UIVisualEffectContentView:0x7ff493e09d70.trailing   (inactive)>
	When added to a view, the constraint's items must be descendants of that view (or the view itself). This will crash if the constraint needs to be resolved before the view hierarchy is assembled. Break on -[UIView(UIConstraintBasedLayout) _viewHierarchyUnpreparedForConstraint:] to debug.
2020-04-17 09:15:14.149650+0200 Example[3330:67265] [LayoutConstraints] The view hierarchy is not prepared for the constraint: <NSLayoutConstraint:0x600002bbe990 UIVisualEffectView:0x7ff493e09b90.bottom == _UIVisualEffectContentView:0x7ff493e09d70.bottom   (inactive)>
	When added to a view, the constraint's items must be descendants of that view (or the view itself). This will crash if the constraint needs to be resolved before the view hierarchy is assembled. Break on -[UIView(UIConstraintBasedLayout) _viewHierarchyUnpreparedForConstraint:] to debug.
2020-04-17 09:15:14.149845+0200 Example[3330:67265] [LayoutConstraints] The view hierarchy is not prepared for the constraint: <NSLayoutConstraint:0x600002bbe9e0 _UIVisualEffectContentView:0x7ff493e09d70.leading == UIVisualEffectView:0x7ff493e09b90.leading   (inactive)>
	When added to a view, the constraint's items must be descendants of that view (or the view itself). This will crash if the constraint needs to be resolved before the view hierarchy is assembled. Break on -[UIView(UIConstraintBasedLayout) _viewHierarchyUnpreparedForConstraint:] to debug.

**Comment by futuretap** [comment]
Thanks, @gereons. I've fixed the warning by embedding the inner visual effect view into a container view. Constraining the visual effect view directly in the stack view seems to be problematic.

I also improved action sheet to support custom content views alongside title and message labels – the same way as alert views do. Previously, setting a contentView disabled the title and message labels in action sheets.

@sberrevoets, now it would be a good time to pull ;)

**Comment by sberrevoets** [comment]
Lot of changes here, but I'll try to get to it this weekend. In the meantime can you squash all the commits so this becomes a clean merge? Thanks!

**Comment by futuretap** [comment]
OK, created #303 squashing all commits into one.

**Pull request closed without merging**
