### PR TITLE
Fix bug: bold cancel button

### PR DESCRIPTION
**Pull request by adamkaplan**
Native dialogs show bold "grant" buttons on the right.

### CODE REVIEW

**Comment by sberrevoets** [comment]
I believe that with the introduction of `UIAlertController`, the creator of an alert has the option to place the cancel button where they want. What you say is true for `UIAlertView`, but this doesn't fix that.

Furthermore, this fix is actually the opposite of what you intended: you are now making all non-cancel buttons bold, and the cancel buttons the normal font.

**Comment by adamkaplan** [comment]
You're right in that this fix would introduce a different bug. I think the framework should produce the least surprise, and cancel being bold was a surprise.

Perhaps a new explicit bold type, and/or some logic around making the right/last button bold if no other bold is specified?

**Comment by adamkaplan** [comment]
By the way: https://github.com/yahoo/YMPromptKit

Thanks!
Also, the bug is present in those screenshots.

**Comment by sberrevoets** [comment]
Hey, that's pretty cool! Thanks!

I wanted to keep this as functionally close to `UIAlertController` as possible. That means that there is no explicit bold or cancel button. I'm not entirely sure what you're trying to do, but the order in which you add buttons is the order in which they are shown. Is it an option to simply change the order in which you add buttons?

If that's not an option, you could always go a little deeper and use a visual style subclass.

**Comment by adamkaplan** [comment]
I'm emulating an OS permissions dialog, which is formatted as [Dont Allow] [*OK*]. The OK is actually heavier, maybe that is the missing piece in this discussion: https://bhaveshdhaduk.files.wordpress.com/2014/07/apns.jpg

I can't change the order. If the soft prompt affirmative button doesn't match the position of the subsequent OS affirmative button it will result in misclicks and opt-outs.

In the case of SDC, cancel (the style) is actually heavier than accept (default?). Perhaps the style names could be more indicative of what they do, because my problem would be solved simply by setting the style of the OK button "Cancel". This mismatch is why I figured it was a bug.

**Comment by sberrevoets** [comment]
When I said change the order in which you add buttons, I meant just the button style. So, in your case, you would first add the "Don't allow" button with a "normal" style, then add an "OK" button with "cancel" style. That seems a little counter-intuitive, but like I said: that's how Apple uses them.

I'm not sure which exact snippet you're talking about when you say that `SDCAlertController` doesn't match `UIAlertController`. Can you give some sample code that in which a `UI` alert does not produce the same result as an `SDC` alert?

**Comment by adamkaplan** [comment]
I can change the style, but it still seems like a bug in the behavior of SDC. Here is a some code for `UIAlertController` translated directly into `SDCAlertController`. The results are clearly different. What am I missing?

```
UIAlertController *alert = [UIAlertController alertControllerWithTitle:@"UIKit" message:@"Message" preferredStyle:UIAlertControllerStyleAlert];
[alert addAction:[UIAlertAction actionWithTitle:@"Don't Allow" style:UIAlertActionStyleCancel handler:nil]];
[alert addAction:[UIAlertAction actionWithTitle:@"OK" style:UIAlertActionStyleDefault handler:nil]];
[self presentViewController:alert animated:YES completion:nil];
```
screenshot 2015-02-18 10 32 47

```
SDCAlertController *alert = [SDCAlertController alertControllerWithTitle:@"SDC" message:@"Message" preferredStyle:SDCAlertControllerStyleAlert];
[alert addAction:[SDCAlertAction actionWithTitle:@"Don't Allow" style:SDCAlertActionStyleCancel handler:nil]];
[alert addAction:[SDCAlertAction actionWithTitle:@"OK" style:SDCAlertActionStyleDefault handler:nil]];
[self presentViewController:alert animated:YES completion:nil];
```

screenshot 2015-02-18 10 32 59

Overlaying the buttons, SDC over UIKit, I get this:
screenshot 2015-02-18 10 32 111

The color and pixel-perfect differences are not very interesting, but emphasizing the 'negative' button is a UX issue.

**Comment by sberrevoets** [comment]
Hmm, yeah, that is an issue. Not liking that, because I thought Apple gave us more freedom in how we ordered our buttons, but it looks like they just straight up override the style if it doesn't follow the HIG :expressionless:

Anyway, if you want to submit a PR that fixes this particular issue, feel free to. Otherwise, I'll take a look at it within the next couple of days.

**Comment by adamkaplan** [comment]
I do have a proposed fix and I'll push it to this PR. You may have a better idea that aligns more closely with the internal project architecture.

**Comment by sberrevoets** [comment]
Yeah, there's always a risk, but if the fix is in line with the idea of the alert (resemble `UIAlertController` as much as possible, but improving the functionality in a logical manner), it's unlikely I'll completely reject it. Just a heads-up: I am pretty nitpicky about coding style/formatting :smiley:

**Comment by adamkaplan** [comment]
I work at Yahoo: my life is one long series of code reviews...

**Comment by adamkaplan** [comment]
(for the record I wasn't able to get the project to compile – something wrong with Pod script paths. I only ran this implementation from within YMPromptKit)

**Comment by sberrevoets** [comment]
I finally had some time to investigate this. Some things I noticed (notation is left to right or top to bottom) in button styling and order:

1. (`Default`, `Default`) -> (normal, bold)
2. (`Cancel`, `Default`) -> (normal, bold)
3. (`Cancel`, `Destructive`) -> (normal, red/bold)
4. (`Default`, `Cancel`, `Default`) -> (normal, normal, bold) - the order of the buttons is changed here so the titles don't match the order in which they were added

I don't see an easy rule or pattern that can be applied here. I spent hours upon hours trying different combinations when I first wrote `SDCAlertView` trying to get it right, and it's just not worth it—especially since the control is supposed to provide more customization.

All in all, I think this is one of the few exceptions where keeping it simple and more customizable is the right call. To make this a little clearer, we can:

1. Update the definition of `SDCAlertActionStyle` to the following:

```objc
typedef NS_OPTIONS(NSInteger, SDCAlertActionStyle) {
	SDCAlertActionStyleDefault = 0
	SDCAlertActionStyleRecommended = 0 << 1 // bold
	SDCAlertActionStyleDestructive = 0 << 2
	SDCAlertActionStyleCancel = SDCAlertActionStyleRecommended
};
```

The Recommended style makes button titles explicitly bold without implying that it's a "cancel" button. And by making it a mask, the Recommended and Destructive styles can be combined for a bold red button. It's flexible, you can achieve the same thing

I'm leaning toward an implementation like this, unless you have strong objections.

**Comment by gereons** [comment]
+1

**Comment by adamkaplan** [comment]
+1

Works for me.

**Comment by sberrevoets** [comment]
I just pushed an update with these changes. Before I update the CocoaPods version as well, can you integrate this in YMPromptKit to see if the changes are compatible and don't break anything?

**Comment by adamkaplan** [comment]
:+1: Works

**Comment by sberrevoets** [comment]
Excellent. I've just updated the version in CocoaPods, these changes are effective in 2.3. Thanks a lot for your input, even if your changes weren't ultimately merged.

**Pull request closed without merging**
