### PR TITLE
Fix Content view width

### PR DESCRIPTION
**Pull request by omartio**

### CODE REVIEW

**Comment by sberrevoets** [comment]
Can you explain the problem a little more?

**Comment by omartio** [comment]
There were missing a contentView width constraint

**Comment by maxflex** [comment]
@sberrevoets давай мёрджи не выёбывайся. Без лишних вопросов

**Comment by sberrevoets** [comment]
There aren't any Auto Layout warnings, does this cause a wrong layout in some cases? If so, how can I reproduce that?

**Comment by sberrevoets** [comment]
Feel free to reopen and explain the problem in some more detail if this is still relevant!

**Pull request closed without merging**
